Codigo/CoAuto/CoAutoWeb/Models/PessoaViewModel.cs
using System.ComponentModel.DataAnnotations;
using Core;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoAutoWeb.Models;

public class PessoaViewModel
{
    [Key]
    public uint Id { get; set; }

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(50, ErrorMessage = "Nome deve ter no máximo 50 caracteres")]
    public string Nome { get; set; } = null!;

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(50, ErrorMessage = "Email deve ter no máximo 50 caracteres")]
    public string Email { get; set; } = null!;

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(9, ErrorMessage = "CNH deve ter no máximo 9 caracteres")]
    public string Cnh { get; set; } = null!;

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(11, ErrorMessage = "CPF deve ter no máximo 11 caracteres")]
    public string Cpf { get; set; } = null!;

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(50, ErrorMessage = "Senha deve ter no máximo 50 caracteres")]
    public string Senha { get; set; } = null!;

    public byte[]? Fotocnh { get; set; }

    [Display(Name = "Data de Nascimento")]
    [Required(ErrorMessage = "Campo requerido")]
    [DataType(DataType.Date)]
    public DateTime DataNascimento { get; set; }

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(14, ErrorMessage = "Telefone deve ter no máximo 14 caracteres")]
    public string Telefone { get; set; } = null!;

    public byte[]? Fotoperfil { get; set; }

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(8, ErrorMessage = "CEP deve ter no máximo 8 caracteres")]
    public string Cep { get; set; } = null!;

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(2, ErrorMessage = "Estado deve ter no máximo 2 caracteres")]
    public string Estado { get; set; } = null!;

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(20, ErrorMessage = "Cidade deve ter no máximo 20 caracteres")]
    public string Cidade { get; set; } = null!;

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(50, ErrorMessage = "Bairro deve ter no máximo 50 caracteres")]
    public string Bairro { get; set; } = null!;

    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(50, ErrorMessage = "Rua deve ter no máximo 50 caracteres")]
    public string Rua { get; set; } = null!;

    [Display(Name = "Número")]
    [Required(ErrorMessage = "Campo requerido")]
    [StringLength(10, ErrorMessage = "Número deve ter no máximo 10 caracteres")]
    public string Numero { get; set; } = null!;

    [StringLength(10, ErrorMessage = "Agência deve ter no máximo 10 caracteres")]
    public string? Agencia { get; set; }

    [Display(Name = "Conta Corrente")]
    [StringLength(10, ErrorMessage = "Conta Corrente deve ter no máximo 10 caracteres")]
    public string? ContaCorrente { get; set; }

    [Display(Name = "Chave Pix")]
    [StringLength(32, ErrorMessage = "Chave Pix deve ter no máximo 32 caracteres")]
    public string? Chavepix { get; set; }

    [Display(Name = "Data Autorização")]
    public DateTime? DataAutorizacao { get; set; }

    [Required(ErrorMessage = "Campo requerido")]
    public sbyte Autorizado { get; set; } = 0;

    [Required(ErrorMessage = "Campo requerido")]
    public string Tipo { get; set; } = "cliente";

    [Required(ErrorMessage = "Campo requerido")]
    public uint IdBanco { get; set; }

    public SelectList? ListaBancos { get; set; }



}

Codigo/CoAuto/CoAutoWeb/Controllers/AluguelController.cs
using AutoMapper;
using CoAutoWeb.Models;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoAutoWeb.Controllers;
[Authorize]
public class AluguelController : Controller
{
    private readonly IAluguelService _aluguelService;
    private readonly IMapper _mapper;
    public AluguelController(IAluguelService aluguelService, IMapper mapper)
    {
        _aluguelService = aluguelService;
        _mapper = mapper;
    }
    // GET: AluguelController
    public ActionResult Index()
    {
        var listaAluguels = _aluguelService.GetAll();
        var listaAluguelsModel = _mapper.Map<List<AluguelViewModel>>(listaAluguels);
        return View(listaAluguelsModel);
    }
    // GET: AluguelController/Details/5
    public ActionResult Details(uint id)
    {
        Aluguel aluguel = _aluguelService.Get(id);
        AluguelViewModel aluguelModel = _mapper.Map<AluguelViewModel>(aluguel);
        return View(aluguelModel);
    }
    // GET: AluguelController/Create
    public ActionResult Create()
    {
        return View();
    }
    // POST: AluguelController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(AluguelViewModel aluguelModel)
    {
        if (ModelState.IsValid)
        {
            var aluguel = _mapper.Map<Aluguel>(aluguelModel);
            _aluguelService.Create(aluguel);
        }
        return RedirectToAction(nameof(Index));
    }
    // GET: AluguelController/Edit/5
    public ActionResult Edit(uint id)
    {
        return Details(id);
    }
    // POST: AluguelController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(uint id, AluguelViewModel aluguelModel)
    {
        if (ModelState.IsValid)
        {
            var aluguel = _mapper.Map<Aluguel>(aluguelModel);
            _aluguelService.Edit(aluguel);
        }
        return RedirectToAction(nameof(Index));
    }
    // GET: AluguelController/Delete/5
    public ActionResult Delete(uint id)
    {
        Aluguel aluguel = _aluguelService.Get(id);
        AluguelViewModel aluguelModel = _mapper.Map<AluguelViewModel>(aluguel);
        return View(aluguelModel);
    }
    // POST: AluguelController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(uint id, AluguelViewModel aluguelModel)
    {
        _aluguelService.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

Codigo/CoAuto/CoAutoWeb/Controllers/PessoaController.cs
using AutoMapper;
using CoAutoWeb.Models;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Service;
using System.Security.Claims;

namespace CoAutoWeb.Controllers;
[Authorize]
public class PessoaController : Controller
{
    private readonly IPessoaService _pessoaService;
    private readonly IBancoService _bancoService;
    private readonly IMapper _mapper;


    public PessoaController(IPessoaService pessoaService, IMapper mapper, IBancoService bancoService)
    {
        _pessoaService = pessoaService;
        _bancoService = bancoService;
        _mapper = mapper;
    }

    // GET: PessoaController
    public ActionResult Index()
    {
        var listaPessoas = _pessoaService.GetAll();
        var listaPessoasModel = _mapper.Map<List<PessoaViewModel>>(listaPessoas);
        return View(listaPessoasModel);
    }

    // GET: PessoaController/Details/5
    public ActionResult Details(uint id)
    {
        Pessoa pessoa = _pessoaService.Get(id);
        PessoaViewModel pessoaModel = _mapper.Map<PessoaViewModel>(pessoa);
        return View(pessoaModel);
    }

    // GET: PessoaController/Create
    public ActionResult Create()
    {
        PessoaViewModel pessoaViewModel = new();
        IEnumerable<Banco> listaBancos = _bancoService.GetAll();
        pessoaViewModel.ListaBancos = new SelectList(listaBancos, "Id", "Nome", null);
        return View(pessoaViewModel);
    }

    // POST: PessoaController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(PessoaViewModel pessoaModel)
    {
        if (ModelState.IsValid)
        {
            var pessoa = _mapper.Map<Pessoa>(pessoaModel);
            pessoa.Email = User.FindFirstValue(ClaimTypes.Email);
            _pessoaService.Create(pessoa);
        }
        return RedirectToAction(nameof(Profile));
    }

    // GET: PessoaController/Edit/5
    public ActionResult Edit(uint id)
    {
        Pessoa? pessoa = _pessoaService.Get(id);
        PessoaViewModel pessoaViewModel = _mapper.Map<PessoaViewModel>(pessoa);
        IEnumerable<Banco> listaBancos = _bancoService.GetAll();
        pessoaViewModel.ListaBancos = new SelectList(listaBancos, "Id","Nome",listaBancos.FirstOrDefault(e=> e.Id.Equals(pessoa.IdBanco)));
        return View(pessoaViewModel);
    }

    // POST: PessoaController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(uint id, PessoaViewModel pessoaModel)
    {
        if (ModelState.IsValid)
        {
            var pessoa = _mapper.Map<Pessoa>(pessoaModel);
            _pessoaService.Edit(pessoa);
        }
        return RedirectToAction(nameof(Index));
    }

    // GET: PessoaController/Delete/5
    public ActionResult Delete(uint id)
    {
        Pessoa pessoa = _pessoaService.Get(id);
        PessoaViewModel pessoaModel = _mapper.Map<PessoaViewModel>(pessoa);
        return View(pessoaModel);
    }

    // POST: PessoaController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(uint id, PessoaViewModel pessoaModel)
    {
        _pessoaService.Delete(id);
        return RedirectToAction(nameof(Index));
    }

    //GET: PessoaControler/Perfil
    [Authorize]
    public ActionResult Profile()
    {
        var userEmailFromToken = User.FindFirstValue(ClaimTypes.Email);
        Console.WriteLine(userEmailFromToken);
        //Obter dados da pessoa || alugueis
        Pessoa pessoa = _pessoaService.GetPerfilParcial(userEmailFromToken);

        PerfilViewModel perfilViewModel = new PerfilViewModel();

        if(pessoa == null)
        {
            perfilViewModel.possuiCadastro = false;
            return View(perfilViewModel);
        }
        else
        {
            perfilViewModel.possuiCadastro = true;
            perfilViewModel = _mapper.Map<PerfilViewModel>(pessoa);
            return View(perfilViewModel);
        }

    }

}

Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Create.cshtml
@model CoAutoWeb.Models.PessoaViewModel

@{
    ViewData["Title"] = "Create";
}

<h5>Adicionar dados ao perfil</h5>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">@Model.Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="Cnh" class="control-label"></label>
                        <input asp-for="Cnh" class="form-control" />
                        <span asp-validation-for="Cnh" class="text-danger"></span>
                    </div>

                    <div class="col-md-6">
                        <label asp-for="Cpf" class="control-label"></label>
                        <input asp-for="Cpf" class="form-control" />
                        <span asp-validation-for="Cpf" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="DataNascimento" class="control-label"></label>
                        <input asp-for="DataNascimento" class="form-control" />
                        <span asp-validation-for="DataNascimento" class="text-danger"></span>
                    </div>

                    <div class="col-md-6">
                        <label asp-for="Telefone" class="control-label"></label>
                        <input asp-for="Telefone" class="form-control" />
                        <span asp-validation-for="Telefone" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <input asp-for="Cep" class="form-control" />
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rua" class="control-label"></label>
                <input asp-for="Rua" class="form-control" />
                <span asp-validation-for="Rua" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="Bairro" class="control-label"></label>
                        <input asp-for="Bairro" class="form-control" />
                        <span asp-validation-for="Bairro" class="text-danger"></span>
                    </div>

                    <div class="col-md-6">
                        <label asp-for="Numero" class="control-label"></label>
                        <input asp-for="Numero" class="form-control" />
                        <span asp-validation-for="Numero" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-8">
                        <label asp-for="IdBanco" class="control-label"></label>
                        <select asp-for="IdBanco" asp-items="@Model.ListaBancos" class="form-control"></select>
                        <span asp-validation-for="IdBanco" class="text-danger"></span>
                    </div>

                    <div class="col-md-4">
                        <label asp-for="Agencia" class="control-label"></label>
                        <input asp-for="Agencia" class="form-control" />
                        <span asp-validation-for="Agencia" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ContaCorrente" class="control-label"></label>
                <input asp-for="ContaCorrente" class="form-control" />
                <span asp-validation-for="ContaCorrente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Chavepix" class="control-label"></label>
                <input asp-for="Chavepix" class="form-control" />
                <span asp-validation-for="Chavepix" class="text-danger"></span>
            </div>
     
            <div class="form-group my-2">
                <input type="submit" value="Salvar" class="btn btn-success" />
                    <a asp-action="Profile" class="btn btn-danger">Cancelar</a>
            </div>

        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Delete.cshtml
@model CoAutoWeb.Models.PessoaViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PessoaModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cnh)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cnh)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cpf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Senha)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Senha)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fotocnh)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fotocnh)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fotoperfil)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fotoperfil)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rua)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rua)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Agencia)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Agencia)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContaCorrente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContaCorrente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Chavepix)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Chavepix)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataAutorizacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataAutorizacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Autorizado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Autorizado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdBanco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdBanco)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Profile.cshtml
@model CoAutoWeb.Models.PerfilViewModel;

<h1>Meu perfil</h1>

<div class="d-flex justify-content-between align-items-center mb-4">
    <partial name="_Profile" model="Model" />

    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPFR-snlw_Lh0NqQAyvxHV6tIsM5JvCQ_5SH1bjVonUX98GKF2ideqhq87-QAdr9FyVBs&usqp=CAU"
         alt="Foto de perfil de @Model.Nome"
         class="rounded-circle img-fluid"
         style="width: 150px; height: 150px; object-fit: cover;">
</div>


@if (Model.possuiCadastro == false)
{
        <a asp-action="Create" asp-controller="Pessoa" class="btn btn-primary">Adicione seus dados</a>
}
else
{
    <div class="row">
        <a asp-action="Edit" asp-controller="Pessoa" class="btn btn-warning">Editar dados</a>
    </div>
}

<h5>Aluguéis</h5>
@if (Model.Alugueis.Count <= 0)
{
    <div class="card">
        <div class="card-body text-center">
            <p class="card-text text-muted">
                Você ainda não realizou nenhum aluguel.
            </p>
            <a asp-controller="Aluguel" asp-action="Index" class="btn btn-primary">Ver veículos disponíveis</a>
        </div>
    </div>
}
@foreach (var aluguel in Model.Alugueis)
{

    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top">
        <div class="card-body">
            <h5 class="card-title">@aluguel.Modelo.Nome</h5>
            <h4 class="card-subtitle mb-2 text-muted">@aluguel.Veiculo.Placa</h4>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@aluguel.DataHoraAluguel</li>
            <li class="list-group-item">@aluguel.Status</li>
            <li class="list-group-item">@aluguel.Pagamento.Valor</li>
        </ul>
        <div class="card-body">
            <a href="#" class="card-link">Detalhes</a>
        </div>
    </div>
    }

<h4><strong>Avaliações</strong></h4>

Codigo/CoAuto/CoAutoWeb/Views/Pessoa/_Profile.cshtml
@model CoAutoWeb.Models.PerfilViewModel;
<div class="mb-3">
<dl>
    <dt class="col-sm-3">Nome</dt>
        <input type="text" id="nomeUsuario" name="nomeUsuario" value="@Model.Nome" class="form-control" disabled readonly>
    <dt class="col-sm-3">Email</dt>
        <input class="form-control" value="@Model.Email" disabled readonly></input>
    <dt class="col-sm-3">CPF</dt>
        <input class="form-control" value="@Model.Cpf" disabled readonly></dd>
    <dt class="col-sm-3">CNH</dt>
        <input class="form-control" value="@Model.Cnh" disabled readonly></dd>
    <dt class="col-sm-3">Telefone</dt>
        <input class="form-control" value="@Model.Telefone" disabled readonly></dd>
    <dt class="col-sm-3">CEP</dt>
        <input class="form-control" value="@Model.Cep" disabled readonly></input>
    <dt class="col-sm-3">Cidade</dt>
        <input class="form-control" value="@Model.Cidade" disabled readonly></input>
    <dt class="col-sm-3">Estado</dt>
        <input class="form-control" value="@Model.Estado" disabled readonly></input>
    <dt class="col-sm-3">Bairro</dt>
        <input class="form-control" value="@Model.Bairro" disabled readonly></input>
    <dt class="col-sm-3">Rua</dt>
        <input class="form-control" value="@Model.Rua" disabled readonly></input>
    <dt class="col-sm-3">Número</dt>
        <input class="form-control" value="@Model.Numero" disabled readonly></input>
</dl>
</div>