Codigo/CoAuto/CoAutoWeb/Controllers/BancoController.cs
using AutoMapper;
using CoAutoWeb.Models;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Mvc;

namespace CoAutoWeb.Controllers;

public class BancoController : Controller
{
    private readonly IBancoService _bancoService;
    private readonly IMapper _mapper;
    public BancoController(IBancoService bancoService, IMapper mapper)
    {
        _bancoService = bancoService;
        _mapper = mapper;
    }
    // GET: BancoController
    public ActionResult Index()
    {
        var listaBancos = _bancoService.GetAll();
        var listaBancosModel = _mapper.Map<List<BancoViewModel>>(listaBancos);
        return View(listaBancosModel);
    }
    // GET: BancoController/Details/5
    public ActionResult Details(uint id)
    {
        Banco banco = _bancoService.Get(id);
        BancoViewModel bancoModel = _mapper.Map<BancoViewModel>(banco);
        return View(bancoModel);
    }
    // GET: BancoController/Create
    public ActionResult Create()
    {
        return View();
    }
    // POST: BancoController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(BancoViewModel bancoModel)
    {
        if (ModelState.IsValid)
        {
            var banco = _mapper.Map<Banco>(bancoModel);
            _bancoService.Create(banco);
        }
        return RedirectToAction(nameof(Index));
    }
    // GET: BancoController/Edit/5
    public ActionResult Edit(uint id)
    {
        return Details(id);
    }
    // POST: BancoController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(uint id, BancoViewModel bancoModel)
    {
        if (ModelState.IsValid)
        {
            var banco = _mapper.Map<Banco>(bancoModel);
            _bancoService.Edit(banco);
        }
        return RedirectToAction(nameof(Index));
    }
    // GET: BancoController/Delete/5
    public ActionResult Delete(uint id)
    {
        Banco banco = _bancoService.Get(id);
        BancoViewModel bancoModel = _mapper.Map<BancoViewModel>(banco);
        return View(bancoModel);
    }
    // POST: BancoController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(uint id, BancoViewModel bancoModel)
    {
        _bancoService.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

Codigo/CoAuto/CoAutoWeb/Controllers/MarcaController.cs
using AutoMapper;
using CoAutoWeb.Models;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoAutoWeb.Controllers;
[Authorize]
public class MarcaController : Controller
{
    private readonly IMarcaService _marcaService;
    private readonly IMapper _mapper;
    public MarcaController(IMarcaService marcaService, IMapper mapper)
    {
        _marcaService = marcaService;
        _mapper = mapper;
    }
    // GET: MarcaController
    public ActionResult Index()
    {
        var listaMarcas = _marcaService.GetAll();
        var listaMarcasModel = _mapper.Map<List<MarcaViewModel>>(listaMarcas);
        return View(listaMarcasModel);
    }
    // GET: MarcaController/Details/5
    public ActionResult Details(uint id)
    {
        Marca marca = _marcaService.Get(id);
        MarcaViewModel marcaModel = _mapper.Map<MarcaViewModel>(marca);
        return View(marcaModel);
    }
    // GET: MarcaController/Create
    public ActionResult Create()
    {
        return View();
    }
    // POST: MarcaController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(MarcaViewModel marcaModel)
    {
        if (ModelState.IsValid)
        {
            var marca = _mapper.Map<Marca>(marcaModel);
            _marcaService.Create(marca);
        }
        return RedirectToAction(nameof(Index));
    }
    // GET: MarcaController/Edit/5
    public ActionResult Edit(uint id)
    {
        return Details(id);
    }
    // POST: MarcaController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(uint id, MarcaViewModel marcaModel)
    {
        if (ModelState.IsValid)
        {
            var marca = _mapper.Map<Marca>(marcaModel);
            _marcaService.Edit(marca);
        }
        return RedirectToAction(nameof(Index));
    }
    // GET: MarcaController/Delete/5
    public ActionResult Delete(uint id)
    {
        Marca marca = _marcaService.Get(id);
        MarcaViewModel marcaModel = _mapper.Map<MarcaViewModel>(marca);
        return View(marcaModel);
    }
    // POST: MarcaController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(uint id, MarcaViewModel marcaModel)
    {
        _marcaService.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

Codigo/CoAuto/CoAutoWeb/Controllers/ModeloController.cs
using AutoMapper;
using CoAutoWeb.Models;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoAutoWeb.Controllers;

public class ModeloController : Controller
{
    private readonly IModeloService _modeloService;
    private readonly IMarcaService _marcaService;
    private readonly IMapper _mapper;
    public ModeloController(IModeloService modeloService, IMarcaService marcaService, IMapper mapper)
    {
        _modeloService = modeloService;
        _marcaService = marcaService;
        _mapper = mapper;
    }

    [HttpGet]
    /// <summary>
    /// Retorna todos os modelos da ViewModel
    /// </summary>
    /// <returns>View(modelos)</returns>
    public ActionResult Index()
    {
        var modelos = _modeloService.GetAll();

        if (modelos == null) return BadRequest();

        var marcas = _marcaService.GetAll();
        var modeloModel = modelos.Select(modelo => new ModeloViewModel
        {
            Id = modelo.Id,
            IdMarca = modelo.IdMarca,
            Nome = modelo.Nome
        }).ToList();
        return View(modeloModel);
    }

    // GET: ModeloController/Details/5
    [HttpGet]
    public ActionResult Details(uint id)
    {
        var modelo = _modeloService.Get(id);

        if (modelo == null) return BadRequest();

        var marcas = _marcaService.GetAll();
        var modeloModel = new ModeloViewModel
        {
            Id = modelo.Id,
            IdMarca = modelo.IdMarca,
            Nome = modelo.Nome
        };
        return View(modeloModel);
    }

    // GET: ModeloController/Create
    public ActionResult Create()
    {
        var marcas = _marcaService.GetAll();
        var items = marcas.Select(marca => new SelectListItem { Value = marca.Id.ToString(), Text = marca.Nome }).ToList();
        var selectList = new SelectList(items, "Value", "Text");
        ViewBag.MarcasSelectList = selectList;
        return View();
    }

    // POST: ModeloController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(ModeloViewModel modeloModel)
    {
        if (ModelState.IsValid)
        {
            try
            {
                var modelo = _mapper.Map<Modelo>(modeloModel);
                _modeloService.Create(modelo);
            }
            catch
            {
                return View(modeloModel);
            }
            return RedirectToAction(nameof(Index));
        }
        return View(modeloModel);
    }

    // GET: ModeloController/Edit/5
    public ActionResult Edit(uint id)
    {
        var modelo = _modeloService.Get(id);
        var modeloModel = _mapper.Map<ModeloViewModel>(modelo);
        var marcas = _marcaService.GetAll();
        var items = marcas.Select(marca => new SelectListItem { Value = marca.Id.ToString(), Text = marca.Nome }).ToList();
        var selectList = new SelectList(items, "Value", "Text");
        ViewBag.MarcasSelectList = selectList;
        return View(modeloModel);
    }

    // POST: ModeloController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(uint id, ModeloViewModel modeloModel)
    {
        if (id != modeloModel.Id) return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                var modelo = _mapper.Map<Modelo>(modeloModel);
                _modeloService.Edit(modelo);
            }
            catch
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }
        return View(modeloModel);
    }

    // GET: ModeloController/Delete/5
    [HttpGet]
    public ActionResult Delete(uint? id)
    {
        if (id == null) return BadRequest();

        var modelo = _modeloService.Get((uint)id);

        if (modelo == null) return NotFound();

        var marcas = _marcaService.GetAll();
        var modeloModel = new ModeloViewModel
        {
            Id = modelo.Id,
            IdMarca = modelo.IdMarca,
            Nome = modelo.Nome
        };
        return View(modeloModel);
    }

    // POST: ModeloController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(uint id)
    {
        _modeloService.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

Codigo/CoAuto/CoAutoWeb/Controllers/PessoaController.cs
using AutoMapper;
using CoAutoWeb.Models;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Service;
using System.Security.Claims;

namespace CoAutoWeb.Controllers;
[Authorize]
public class PessoaController : Controller
{
    private readonly IPessoaService _pessoaService;
    private readonly IBancoService _bancoService;
    private readonly IMapper _mapper;


    public PessoaController(IPessoaService pessoaService, IMapper mapper, IBancoService bancoService)
    {
        _pessoaService = pessoaService;
        _bancoService = bancoService;
        _mapper = mapper;
    }

    // GET: PessoaController
    public ActionResult Index()
    {
        var listaPessoas = _pessoaService.GetAll();
        var listaPessoasModel = _mapper.Map<List<PessoaViewModel>>(listaPessoas);
        return View(listaPessoasModel);
    }

    // GET: PessoaController/Details/5
    public ActionResult Details(uint id)
    {
        Pessoa pessoa = _pessoaService.Get(id);
        PessoaViewModel pessoaModel = _mapper.Map<PessoaViewModel>(pessoa);
        return View(pessoaModel);
    }

    // GET: PessoaController/Create
    public ActionResult Create()
    {
        PessoaViewModel pessoaViewModel = new();
        IEnumerable<Banco> listaBancos = _bancoService.GetAll();
        pessoaViewModel.ListaBancos = new SelectList(listaBancos, "Id", "Nome", null);
        return View(pessoaViewModel);
    }

    // POST: PessoaController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(PessoaViewModel pessoaModel)
    {
        if (ModelState.IsValid)
        {
            var pessoa = _mapper.Map<Pessoa>(pessoaModel);
            pessoa.Email = User.FindFirstValue(ClaimTypes.Email);
            _pessoaService.Create(pessoa);
        }
        return RedirectToAction(nameof(Profile));
    }

    // GET: PessoaController/Edit/5
    public ActionResult Edit(uint id)
    {
        Pessoa? pessoa = _pessoaService.Get(id);
        PessoaViewModel pessoaViewModel = _mapper.Map<PessoaViewModel>(pessoa);
        IEnumerable<Banco> listaBancos = _bancoService.GetAll();
        pessoaViewModel.ListaBancos = new SelectList(listaBancos, "Id","Nome",listaBancos.FirstOrDefault(e=> e.Id.Equals(pessoa.IdBanco)));
        return View(pessoaViewModel);
    }

    // POST: PessoaController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(uint id, PessoaViewModel pessoaModel)
    {
        if (ModelState.IsValid)
        {
            var pessoa = _mapper.Map<Pessoa>(pessoaModel);
            _pessoaService.Edit(pessoa);
        }
        return RedirectToAction(nameof(Index));
    }

    // GET: PessoaController/Delete/5
    public ActionResult Delete(uint id)
    {
        Pessoa pessoa = _pessoaService.Get(id);
        PessoaViewModel pessoaModel = _mapper.Map<PessoaViewModel>(pessoa);
        return View(pessoaModel);
    }

    // POST: PessoaController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(uint id, PessoaViewModel pessoaModel)
    {
        _pessoaService.Delete(id);
        return RedirectToAction(nameof(Index));
    }

    //GET: PessoaControler/Perfil
    [Authorize]
    public ActionResult Profile()
    {
        var userEmailFromToken = User.FindFirstValue(ClaimTypes.Email);
        Console.WriteLine(userEmailFromToken);
        //Obter dados da pessoa || alugueis
        Pessoa pessoa = _pessoaService.GetPerfilParcial(userEmailFromToken);

        PerfilViewModel perfilViewModel = new PerfilViewModel();

        if(pessoa == null)
        {
            perfilViewModel.possuiCadastro = false;
            return View(perfilViewModel);
        }
        else
        {
            perfilViewModel.possuiCadastro = true;
            perfilViewModel = _mapper.Map<PerfilViewModel>(pessoa);
            return View(perfilViewModel);
        }

    }

}

Codigo/CoAuto/CoAutoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoAuto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoAutoWeb.styles.css" asp-append-version="true" />
</head>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <span style="color:red">CO</span>
                <span style="color:blue">AUTO</span>

            </a>
            <partial name="_LoginPartial" />
            </div>
    </nav>
</header>

<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="nav flex-column">
                        <h4>Menu</h4>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pagamento" asp-action="Index">Pagamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluguel" asp-action="Index">Alugueis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Veiculo" asp-action="Index">Veículos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Disponibilidade" asp-action="Index">Disponibilidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="Index">Marcas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Modelo" asp-action="Index">Modelos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Entrega" asp-action="Index">Entregas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Devolucao" asp-action="Index">Devoluções</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Banco" asp-action="Index">Bancos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Profile">Meu perfil</a>
                        </li>

                    </ul>
                </div>
    </nav>


            <main role="main" class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            @RenderBody()
        </main>

    </div>
    </div>
  
</body>
<footer class="border-top footer text-muted mt-1">
    <div class="container">
        &copy; 2023 - CoAutoWeb -
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</html>